# Uygulama Portu
server.port=9000

# Veritaban? Ba?lant? Bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=hello
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Ayarlar?
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# ?lk çal??t?rmada tablo olu?sun, sonra veriler silinmesin diye 'update' yap?yoruz
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Log Seviyeleri (Görev 4 için tam uyum)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
